# environment.yml for running Gantry experiments.

name: base
channels:
  - pytorch
  - nvidia  # Required for cudatoolkit
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - numpy
  - pytorch=2.1
  - tqdm
  - pip